### ISSUE TITLE
Configurable frame per second.

### ISSUE THREAD

**Issue by OfficialIncubo** [delaneyparker/cthugha-js#2]
The Cthugha's default FPS is 30. Can you please implement some functionality to control the FPS from 1-60 or 1-Actual Monitor's hz using the GUI?

**Comment by delaneyparker** [comment]
Thanks for asking! If you hold down shift while holding the + / - keys, it will adjust the frame rate. 
If you don't hold shift, it'll adjust the rate of change between palettes, flames, waves, tabs, etc.

LMK if you would like this functionality added to the GUI as you mentioned in your original post. I'm trying to keep the menu tidy/compact, which is why it's currently a keyboard shortcut.
